from fastapi import APIRouter
from sqlmodel import select

from sqlalchemy.orm import selectinload
from api.core.smtp import send_email
from config import DOMAIN
from src.api.models.role_model.userRoleModel import UserRole
from src.api.core.response import api_response
from src.api.models.role_model.roleModel import Role
from src.api.core.security import create_access_token, exist_user, hash_password
from src.api.core.dependencies import GetSession
from src.api.models.userModel import User, UserCreate, UserRead


router = APIRouter(tags=["Auth"])


@router.post("/init", response_model=UserRead)
def initialize_first_user(
    request: UserCreate,
    session: GetSession,
):

    # Create first user with admin role
    hashed_password = hash_password(request.password)
    user = User(**request.model_dump())
    user = User(
        name=request.name,
        email=request.email,
        phone_no=request.phone_no,
        password=hashed_password,
        is_root=True,
    )
    session.add(user)
    session.flush()
    # Prevent rerun if roles already exist
    existing_roles = session.exec(select(Role)).all()
    if existing_roles:
        return api_response(
            400,
            "Initialization already done",
        )

    # Create roles
    admin_role = Role(
        name="root",
        slug="root",
        user_id=user.id,
        permissions=["all", "system:*"],
    )
    shop_admin_role = Role(
        name="Seller Roles",
        slug="shop_admin",
        user_id=user.id,
        permissions=["shop_admin", "role"],
    )

    session.add(admin_role)
    session.add(shop_admin_role)
    session.flush()  # get IDs without committing

    # Assign admin role to the user via UserRole
    user_role_link = UserRole(user_id=user.id, role_id=admin_role.id)
    session.add(user_role_link)

    session.commit()
    session.refresh(user)

    user_read = UserRead.model_validate(user)
    return api_response(
        200,
        "Initialized admin user and roles",
        user_read,
    )


@router.post("/register", response_model=dict)
def register_user(
    request: UserCreate,
    session: GetSession,
):
    db_user = exist_user(session, email=request.email)
    if db_user:
        return api_response(
            400,
            "This user already exist",
        )
    user = User(**request.model_dump())  # Similar to new User(req.body) in Mongoose
    hashed_password = hash_password(user.password)
    user.password = hashed_password
    session.add(user)
    session.commit()
    session.refresh(user)  # Refresh to get updated fields (e.g., autogenerated ID)

    # ✅ Create JWT token (valid for lifetime)
    token = create_access_token({"id": user.id, "email": user.email})

    verify_url = f"{DOMAIN}/verify/verify-email?token={token}"
    # Load template
    with open("src/templates/email_verification.html") as f:
        html_template = f.read().replace("{{VERIFY_URL}}", verify_url)

    # Send email
    send_email(
        to_email=user.email,
        subject="Verify Your Email Address",
        body=html_template,
    )
    user_read = UserRead.model_validate(user)  # ✅ Convert User → UserRead
    return api_response(
        200,
        "Check Your Email to Verify Your Account",
        user_read,
    )
