"""category name unique on same parent id

Revision ID: 009c23e5ef25
Revises: d98dca4fc5ce
Create Date: 2026-07-17 11:09:09.505226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009c23e5ef25'
down_revision: Union[str, Sequence[str], None] = 'd98dca4fc5ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_name_per_parent', 'categories', ['parent_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_name_per_parent', 'categories', type_='unique')
    # ### end Alembic commands ###
