"""default dealer id

Revision ID: 2288a1091379
Revises: fed189d401ab
Create Date: 2026-04-07 17:57:27.874379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2288a1091379'
down_revision: Union[str, Sequence[str], None] = 'fed189d401ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_default_shop_id'), 'users', ['default_shop_id'], unique=False)
    op.create_foreign_key(None, 'users', 'shops', ['default_shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_default_shop_id'), table_name='users')
    op.drop_column('users', 'default_shop_id')
    # ### end Alembic commands ###
