"""otp auth - make signup fields nullable

Revision ID: 2a8989ffb3bc
Revises: b78dd45fab3c
Create Date: 2026-08-19 11:15:49.365881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8989ffb3bc'
down_revision: Union[str, Sequence[str], None] = 'b78dd45fab3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also proposed re-creating 7 foreign keys here
    # (orders/products/roles/shop_users/shops/user_addresses/user_roles ->
    # users) — that's a known false-positive from the circular FK between
    # shops.owner_id and users.default_shop_id confusing autogenerate's
    # dependency sort ("Cannot correctly sort tables ... unresolvable
    # cycles"). Those FKs already exist; stripped out to avoid duplicating
    # them. Only the intended nullable-column changes remain below.
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'currency_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'currency_symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currency_symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'currency_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
