"""slug remove in role

Revision ID: 434c61724055
Revises: e510a2c1e1fd
Create Date: 2026-04-20 15:59:47.629194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434c61724055'
down_revision: Union[str, Sequence[str], None] = 'e510a2c1e1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_column('roles', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('slug', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    # ### end Alembic commands ###
