"""unique user role

Revision ID: 6a44634cc882
Revises: a5e725182754
Create Date: 2026-04-01 12:38:38.831820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a44634cc882'
down_revision: Union[str, Sequence[str], None] = 'a5e725182754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    # ### end Alembic commands ###
