"""shp[_id added in media

Revision ID: 7ef3917f1147
Revises: a3f7c1d2e9b4
Create Date: 2026-08-05 13:06:27.834871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef3917f1147'
down_revision: Union[str, Sequence[str], None] = 'a3f7c1d2e9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'shop_id')
    # ### end Alembic commands ###
