"""order number update

Revision ID: 7ef668fbbc8c
Revises: 2e2d2314f04a
Create Date: 2026-05-05 16:01:22.822006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef668fbbc8c'
down_revision: Union[str, Sequence[str], None] = '2e2d2314f04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
