"""initialize

Revision ID: 9a2c5fdc5d6c
Revises:
Create Date: 2026-03-17 13:03:55.604427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9a2c5fdc5d6c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "unverified_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column("users", sa.Column("verified", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=False)
    op.create_index(
        "uq_users_phone_verified",
        "users",
        ["phone"],
        unique=True,
        postgresql_where=sa.text("verified = true"),
    )
    op.create_index(
        "uq_users_verified_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email_verified = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_verified_email",
        table_name="users",
        postgresql_where=sa.text("email_verified = true"),
    )
    op.drop_index(
        "uq_users_phone_verified",
        table_name="users",
        postgresql_where=sa.text("verified = true"),
    )
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.drop_column("users", "verified")
    op.drop_column("users", "unverified_phone")
    # ### end Alembic commands ###
