"""product update

Revision ID: b4e74bdde5a8
Revises: 7cf6a77e2ef5
Create Date: 2026-05-11 13:05:40.996271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e74bdde5a8'
down_revision: Union[str, Sequence[str], None] = '7cf6a77e2ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'price')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'is_in_stock')
    op.drop_column('products', 'discount_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    # ### end Alembic commands ###
