"""cart dynamic remove total items and price

Revision ID: e01ee34a6422
Revises: e1e79b628207
Create Date: 2026-06-02 11:40:45.987414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01ee34a6422'
down_revision: Union[str, Sequence[str], None] = 'e1e79b628207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    op.create_unique_constraint('uq_cart_user_shop_status', 'carts', ['user_id', 'shop_id', 'status'])
    op.drop_column('carts', 'total_items')
    op.drop_column('carts', 'subtotal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('total_items', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_cart_user_shop_status', 'carts', type_='unique')
    op.add_column('cart_items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
