"""role_name_unique

Revision ID: e510a2c1e1fd
Revises: de869a3730f9
Create Date: 2026-04-20 12:32:06.685279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e510a2c1e1fd'
down_revision: Union[str, Sequence[str], None] = 'de869a3730f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index('uq_role_name_global', 'roles', ['name'], unique=True, postgresql_where=sa.text('shop_id IS NULL'))
    op.create_unique_constraint('uq_role_name_shop', 'roles', ['name', 'shop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_name_shop', 'roles', type_='unique')
    op.drop_index('uq_role_name_global', table_name='roles', postgresql_where=sa.text('shop_id IS NULL'))
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
