"""order number update

Revision ID: e6b866ba74b7
Revises: e93c7bdc08b2
Create Date: 2026-05-05 15:10:00.851170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b866ba74b7'
down_revision: Union[str, Sequence[str], None] = 'e93c7bdc08b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
