"""short description limit 1000

Revision ID: e9cf4b4ab33c
Revises: 610a2bba72ef
Create Date: 2026-09-10 12:36:02.204862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e9cf4b4ab33c"
down_revision: Union[str, Sequence[str], None] = "610a2bba72ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "orders", "users", ["user_id"], ["id"])
    op.alter_column(
        "products",
        "short_description",
        existing_type=sa.VARCHAR(length=300),
        type_=sqlmodel.sql.sqltypes.AutoString(length=800),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "products", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "roles", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "shop_users", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "shops", "users", ["owner_id"], ["id"])
    op.create_foreign_key(None, "user_addresses", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "user_roles", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_constraint(None, "user_addresses", type_="foreignkey")
    op.drop_constraint(None, "shops", type_="foreignkey")
    op.drop_constraint(None, "shop_users", type_="foreignkey")
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.alter_column(
        "products",
        "short_description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=800),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    # ### end Alembic commands ###
