"""product and shop user added

Revision ID: f9de39311f19
Revises: 1bed70481dab
Create Date: 2026-04-06 16:33:42.824876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f9de39311f19"
down_revision: Union[str, Sequence[str], None] = "1bed70481dab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("discount_price", sa.Float(), nullable=True),
        sa.Column("cost_price", sa.Float(), nullable=True),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("is_in_stock", sa.Boolean(), nullable=False),
        sa.Column("thumbnail", sa.JSON(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column(
            "meta_title", sqlmodel.sql.sqltypes.AutoString(length=191), nullable=True
        ),
        sa.Column(
            "meta_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_price"), "products", ["price"], unique=False)
    op.create_index(op.f("ix_products_shop_id"), "products", ["shop_id"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=False)
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    op.create_table(
        "shop_users",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shop_users_shop_id"), "shop_users", ["shop_id"], unique=False
    )
    op.create_index(
        op.f("ix_shop_users_user_id"), "shop_users", ["user_id"], unique=False
    )
    op.add_column("roles", sa.Column("shop_id", sa.Integer(), nullable=True))
    op.add_column("roles", sa.Column("is_system", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_roles_shop_id"), "roles", ["shop_id"], unique=False)
    op.create_foreign_key(None, "roles", "shops", ["shop_id"], ["id"])
    op.add_column("user_roles", sa.Column("shop_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user_roles", "shops", ["shop_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_roles", type_="foreignkey")
    op.drop_column("user_roles", "shop_id")
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_index(op.f("ix_roles_shop_id"), table_name="roles")
    op.drop_column("roles", "is_system")
    op.drop_column("roles", "shop_id")
    op.drop_index(op.f("ix_shop_users_user_id"), table_name="shop_users")
    op.drop_index(op.f("ix_shop_users_shop_id"), table_name="shop_users")
    op.drop_table("shop_users")
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_shop_id"), table_name="products")
    op.drop_index(op.f("ix_products_price"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
