"""unique user_id shop_id shop child

Revision ID: fed189d401ab
Revises: f9de39311f19
Create Date: 2026-04-07 11:25:46.893926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed189d401ab'
down_revision: Union[str, Sequence[str], None] = 'f9de39311f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shop_user', 'shop_users', ['user_id', 'shop_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shop_user', 'shop_users', type_='unique')
    # ### end Alembic commands ###
